name: RELEASE

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  push-executors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: |
          [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - name: push to Hubble
        id: push_exec
        uses: jina-ai/action-hubble-push@v2
        with:
          git_tag: ${{ steps.get_version.outputs.tag }}
        env:
          exec_uuid: ${{ secrets.UUID }}
          exec_secret: ${{ secrets.SECRET }}
      - run: echo push result ${{ steps.push_exec.outputs.exit_code}}
        shell: bash
